### ISSUE TITLE
Update to support Talos 1.2.6

### ISSUE THREAD

**Issue by shaquille-ozeal** [siderolabs/terraform-provider-talos#26]
What needs to be done to support Talos 1.2.6?

I noticed that SDK changes are merged into this project every time a Talos version is released. Is that all that's needed?

**Comment by frezbo** [comment]
Yes, that's the only thing required. Run `go mod tidy` and generate a new changelog after updating `hack/release.toml`. Some small steps are involved, but at the same time, the provider should work fine for any any talos 1.2 series release, since we don't introduce new machine config fields for minor releases.

**Comment by frezbo** [comment]
fixed by #27 , you could look at the PR for an idea of things to update
